# Generated by Django 3.1.4 on 2020-12-26 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autodj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatorasset',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploader'),
        ),
        migrations.AddField(
            model_name='rotator',
            name='rotator_assets',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='rotators', to='autodj.RotatorAsset', verbose_name='rotator assets'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='audio_assets',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='playlists', to='autodj.AudioAsset', verbose_name='audio assets'),
        ),
        migrations.AddField(
            model_name='audioasset',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploader'),
        ),
    ]
