# Generated by Django 3.1.3 on 2020-11-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioasset',
            options={'ordering': ('title', 'artist', 'album', 'id'), 'verbose_name': 'audio asset', 'verbose_name_plural': 'audio assets'},
        ),
        migrations.AddField(
            model_name='audioasset',
            name='md5sum',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='rotatorasset',
            name='md5sum',
            field=models.UUIDField(null=True),
        ),
    ]
