# Generated by Django 3.1.3 on 2020-12-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodj', '0002_auto_20201130_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioasset',
            name='md5sum',
        ),
        migrations.RemoveField(
            model_name='rotatorasset',
            name='md5sum',
        ),
        migrations.AddField(
            model_name='audioasset',
            name='fingerprint',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rotatorasset',
            name='fingerprint',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
