# Generated by Django 3.1.3 on 2020-11-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastasset',
            options={'ordering': ('title', 'id'), 'verbose_name': 'scheduled broadcast asset', 'verbose_name_plural': 'scheduled broadcast assets'},
        ),
        migrations.AddField(
            model_name='broadcastasset',
            name='md5sum',
            field=models.UUIDField(null=True),
        ),
    ]
