# Generated by Django 3.1.3 on 2020-11-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Unique codename to identify this upstream server.', max_length=20, unique=True, verbose_name='name')),
                ('hostname', models.CharField(help_text='Hostname for the server, eg. example.com', max_length=255, verbose_name='hostname')),
                ('protocol', models.CharField(choices=[('http', 'http'), ('https', 'https (secure)')], default='http', help_text="The protocol for the server, if unsure it's likely http", max_length=5, verbose_name='protocol')),
                ('port', models.PositiveSmallIntegerField(help_text='Port for this server, eg. 8000', verbose_name='port')),
                ('username', models.CharField(default='source', max_length=255, verbose_name='username')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('mount', models.CharField(help_text='Mount point for the upstream server, eg. /stream', max_length=255, verbose_name='mount point')),
                ('encoding', models.CharField(choices=[('m', 'MP3'), ('a', 'AAC'), ('o', 'OGG Vorbis'), ('f', 'ffmpeg (custom)')], default='m', max_length=1, verbose_name='encoding format')),
                ('bitrate', models.PositiveSmallIntegerField(blank=True, help_text='Encoding bitrate (kbits), leave blank for a sane default.', null=True, verbose_name='bitrate')),
                ('encoding_args', models.JSONField(blank=True, default=None, help_text='Enter any additional arguments for the encoder here. Advanced use cases only, see the <a href="https://www.liquidsoap.info/doc-1.4.3/encoding_formats.html" target="_blank">Liquidsoap docs here</a> for more info. Leave empty or <code>null</code> for none.', null=True, verbose_name='additional arguments for encoding')),
            ],
        ),
    ]
