# Generated by Django 3.2rc1 on 2021-03-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamserver',
            name='is_test',
            field=models.BooleanField(default=False, help_text='<strong>Important:</strong> Leave unchecked for live harbor', verbose_name='connect to test harbor (instead of live)'),
        ),
    ]
