# Generated by Django 3.1.3 on 2020-11-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upstreamserver',
            name='telnet_port',
            field=models.PositiveIntegerField(default=1234),
            preserve_default=False,
        ),
    ]
