# Generated by Django 3.1.2 on 2020-10-17 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledBroadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_path', models.CharField(max_length=1024)),
                ('scheduled_time', models.DateTimeField()),
                ('task_id', models.UUIDField(null=True)),
                ('play_status', models.CharField(choices=[('n', 'Newly Created'), ('q', 'Queued'), ('p', 'Played'), ('e', 'Error')], default='n', max_length=1)),
            ],
            options={
                'ordering': ('-scheduled_time',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harbor_auth', models.CharField(choices=[('a', 'Always'), ('n', 'Never'), ('s', 'Schedule Based')], max_length=1)),
                ('early_entry', models.DurationField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=1024, unique=True)),
                ('title', models.CharField(max_length=1024, verbose_name='Title')),
                ('start', models.DateTimeField(verbose_name='Start Time')),
                ('end', models.DateTimeField(verbose_name='End Time')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Authorized Users')),
            ],
            options={
                'verbose_name': 'Google Calendar Show',
                'verbose_name_plural': 'Google Calendar Shows',
            },
        ),
    ]
